### ISSUE TITLE
Generating .npy input format for segmentation with a multi-channel tif

### ISSUE THREAD

**Issue by asmagen** [jlevy44/PathFlowAI#22]
I collected some example data to start working with PFAI, but I need to find a workaround the input formatting. I have a set of tif files where each file has 6 channels corresponding to (1) background (2) tumor (3) normal (4) stroma etc. The libraries I typically use like CV2 and similar counterparts handle only three channels, and the resources I found online seem to discuss only saving 4+ channel files rather than reading and converting. Do you know can I convert my input files to the requested npy format for PFAI segmentation?

Thanks

**Comment by jlevy44** [comment]
I would try tifffile's imread, then write to numpy with np.save .
