### ISSUE TITLE
No such command 'train_model'

### ISSUE THREAD

**Issue by asmagen** [jlevy44/PathFlowAI#25]
I encountered the following issue with running the training:
```
!pathflowai-train_model train_model -h
nonechucks may not work properly with this version of PyTorch (1.5.0). It has only been tested on PyTorch versions 1.0, 1.1, and 1.2
Usage: pathflowai-train_model [OPTIONS] COMMAND [ARGS]...
Try 'pathflowai-train_model -h' for help.

Error: No such command 'train_model'.
```

**Comment by jlevy44** [comment]
Works fine for me. How did you install pathflow?

![image](https://user-images.githubusercontent.com/19698023/82965655-994e5f00-9f7d-11ea-9759-ef44bdb4441d.png)

**Comment by asmagen** [comment]
Now I get

```
!pathflowai-train_model train_model -h
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
	Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
```
after the '512' output from the preprocessing discussed in #24

**Comment by jlevy44** [comment]
I do not think this is an issue on our software’s end. Could be a missing dependency either via singularity or from your HPC. You could also try the recommendation that you had just sent me.
