### ISSUE TITLE
Issue with Transposing Dask Array and Application of Annotations

### ISSUE THREAD

**Issue by jlevy44** [jlevy44/PathFlowAI#26]
There may be an issue associated with https://github.com/jlevy44/PathFlowAI/pull/6 that transposes the dask array from its original orientation.

Debug and PR is needed ASAP.

**Comment by sumanthratna** [comment]
Yikes—I intentionally added a final transpose: https://github.com/jlevy44/PathFlowAI/pull/6/commits/c2b0e54e052261eaeafae842cf365d98003d54ec#diff-bf069ac5bda9fb89424f63378deef48bR127, which was originally commented out. If I remember correctly, this is because the SVS I was testing on got transposed. I'll look into this.

**Comment by sumanthratna** [comment]
Hmmm, I think the final transpose is correct. The napari screenshot is what's loaded via `svs2_daskarray` (spliced with `10000:14000,10000:14000`), and the other screenshot is the ground truth of the approximate region:
![Screen Shot 2020-05-26 at 21 49 03](https://user-images.githubusercontent.com/31281983/82968307-03c1c800-9f9b-11ea-9ac8-d6ae45d7e737.png)
![Screen Shot 2020-05-26 at 21 49 31](https://user-images.githubusercontent.com/31281983/82968308-045a5e80-9f9b-11ea-9d50-45a3546c282c.png)

(TCGA-DD-AADV-01Z-00-DX1)

**Comment by sumanthratna** [comment]
It's strange how I didn't notice that this would be a breaking change. We can:
- restore the previous version (as simple as recommenting the final transpose), but I don't know if this will be correct (see previous screenshots)
- transpose the annotations, which should be as simple as swapping the X and Y coordinates of the annotations

**Comment by jlevy44** [comment]
@lvaickus and I will discuss and see what option we like the best. I’m leaning towards including a transpose with the option to opt out

**Comment by jlevy44** [comment]
I added a transpose option that should be compatible with your software.

Also, there could be issues with utilizing:
https://github.com/jlevy44/PathFlowAI/blob/1b18187ff8fcdac97906902b73c52601e7f7cf75/pathflowai/utils.py#L296
When using the no_zarr option.

I will have to think more about enforcing compatibility with annotations.

**Comment by jlevy44** [comment]
https://github.com/jlevy44/PathFlowAI/commit/74b25ed537b553b67b88ff36ad338da104b9813d

**Comment by jlevy44** [comment]
https://github.com/jlevy44/PathFlowAI/blob/master/pathflowai/utils.py#L127

**Comment by jlevy44** [comment]
I think under the no_zarr specification, running transpose_annotations may work remedy possible issues.

**Comment by jlevy44** [comment]
Okay, the changes fixed things on my end..
